ASP.NET_Core/MVC/04_SimpleWebSite/WebSite/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace WebSite.Models;

public class Contact {

    [Display(Name = "Введите имя:")]
    [Required(ErrorMessage = "Обязательное поле")]
    public string Name { get; set; }

    [Display(Name = "Введите фамилию:")]
    [Required(ErrorMessage = "Обязательное поле")]
    public string Surname { get; set; }

    [Display(Name = "Введите возраст:")]
    [Required(ErrorMessage = "Обязательное поле")]
    public int Age { get; set; }

    [Display(Name = "Введите Email:")]
    [Required(ErrorMessage = "Обязательное поле")]
    public string Email { get; set; }

    [Display(Name = "Введите сообщение:")]
    [Required(ErrorMessage = "Обязательное поле")]
    public string Message { get; set; }
}

ASP.NET_Core/MVC/04_SimpleWebSite/WebSite/Models/ErrorViewModel.cs
namespace WebSite.Models;

public class ErrorViewModel {
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ASP.NET_Core/MVC/04_SimpleWebSite/WebSite/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using WebSite.Models;

namespace WebSite.Controllers;

public class ContactsController : Controller {
    public IActionResult Index() => View();

    [HttpPost]
    public IActionResult Check(Contact contact) {
        if (ModelState.IsValid) {
            return Redirect("/");
        }
        return View("Index");
    }
}

ASP.NET_Core/MVC/04_SimpleWebSite/WebSite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebSite.Models;

namespace WebSite.Controllers;

public class HomeController : Controller {

    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger) => _logger = logger;

    public IActionResult Index() => View();

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error() {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ASP.NET_Core/MVC/04_SimpleWebSite/WebSite/Views/Contacts/Index.cshtml
@model Contact
@{
    ViewData["Title"] = "Обратная связь";
}

<h1>@ViewData["Title"]</h1>

<form method="post" asp-controller="Contacts" asp-action="Check">
    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <span asp-validation-for="Name" />

    <label asp-for="Surname"></label>
    <input asp-for="Surname" />
    <span asp-validation-for="Surname" />

    <label asp-for="Age"></label>
    <input asp-for="Age" />
    <span asp-validation-for="Age" />

    <label asp-for="Email"></label>
    <input asp-for="Email" />
    <span asp-validation-for="Email" />

    <label asp-for="Message"></label>
    <input asp-for="Message" />
    <span asp-validation-for="Message" />

    <input type="submit" value="Отправить" />
</form>