ASP.NET_Core/MVC/02_METANIT_MVCTutorial/07_ViewComponent/Components/TimerViewComponent.cs
namespace _07_ViewComponent.Components;

public class TimerViewComponent {
    public string Invoke() => $"Текущее время: {DateTime.Now.ToString("hh:mm:ss")}";
}

ASP.NET_Core/MVC/02_METANIT_MVCTutorial/07_ViewComponent/Components/UsersListViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace _07_ViewComponent.Components;

public class UsersListViewComponent : ViewComponent {

    List<string> users = new List<string> { "Tom", "Tim", "Bob", "Sam" };

    public IViewComponentResult Invoke() => View(users);
}

ASP.NET_Core/MVC/02_METANIT_MVCTutorial/07_ViewComponent/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace _07_ViewComponent.Controllers;

public class HomeController : Controller {
    public IActionResult Index() => View();
}

ASP.NET_Core/MVC/02_METANIT_MVCTutorial/07_ViewComponent/Views/Home/Components/UsersList/Default.cshtml
@* UsersListViewComponent *@

@model IEnumerable<string>
<h2>Список пользователей</h2>
<ul>
    @foreach (var user in Model) {
        <li>@user</li>
    }
</ul>

ASP.NET_Core/MVC/02_METANIT_MVCTutorial/07_ViewComponent/Views/Home/Index.cshtml
@addTagHelper *, 07_ViewComponent

@await Component.InvokeAsync("Timer")

<h2>-----------------------------</h2>

@* Tag-хелпер vc
   Также мы можем встраивать компонент с помощью тег-хелпера vc в формате
   <vc:[имя_компонента]></vc:[имя_компонента]>
*@

<vc:timer />

<h2>-----------------------------</h2>

<h2>@await Component.InvokeAsync("Header")</h2>

<h2>-----------------------------</h2>

<p>
    24 часовой формат с секундами: <br />
    @await Component.InvokeAsync("Stopwatch", new { includeSeconds = true, format24 = true })
</p>

<p>
    12 часовой формат без секунд: <br />
    <vc:Stopwatch include-seconds="false" format24="false"></vc:Stopwatch>
</p>
<p>
    24 часовой формат без секунд: <br />
    <vc:Stopwatch include-seconds="false" format24="true"></vc:Stopwatch>
</p>

<h2>-----------------------------</h2>

<div>
    @await Component.InvokeAsync("UsersList")
</div>
<div>
    <vc:users-list />
</div>